### ISSUE TITLE
remove the .idea folder

### ISSUE THREAD

**Issue by ananno** [iraihankabir/DeepLearning#3]
.idea folder was created the project profile for pycharm. it will mess up my .idea folder if you keep it in the repository. I've already added this directory in the .gitignore file. Please remove the folder and commit the change.

**Comment by iraihankabir** [comment]
This is showing you are a contributor... already

**Comment by iraihankabir** [comment]
I don't know much about adding contributor. I just ended up adding this..
here's the invitaion-link >> https://github.com/iraihankabir/DeepLearning/invitations
